// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using proyecto100dias.Models;

#nullable disable

namespace proyecto100dias.Migrations
{
    [DbContext(typeof(pieroDbContext))]
    [Migration("20240819041329_migracionInicial")]
    partial class migracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("proyecto100dias.Models.trabajadores", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime?>("fechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("primerApellido")
                        .HasColumnType("text");

                    b.Property<string>("primerNombre")
                        .HasColumnType("text");

                    b.Property<int?>("rutTrabajador")
                        .HasColumnType("integer");

                    b.Property<string>("segundoApellido")
                        .HasColumnType("text");

                    b.Property<string>("segundoNombre")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("trabajadores");
                });
#pragma warning restore 612, 618
        }
    }
}
