// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using proyecto100dias.Models;

#nullable disable

namespace proyecto100dias.Migrations
{
    [DbContext(typeof(pieroDbContext))]
    [Migration("20240821052923_actualizacionModelo")]
    partial class actualizacionModelo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("proyecto100dias.Models.trabajadores", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_trabajador");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateOnly?>("fecha_nacimiento")
                        .HasColumnType("date");

                    b.Property<string>("primer_apellido")
                        .HasColumnType("text");

                    b.Property<string>("primer_nombre")
                        .HasColumnType("text");

                    b.Property<int?>("rut_trabajador")
                        .HasColumnType("integer");

                    b.Property<string>("segundo_apellido")
                        .HasColumnType("text");

                    b.Property<string>("segundo_nombre")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("trabajadores");
                });
#pragma warning restore 612, 618
        }
    }
}
